name: CrownedComedian-t3
version: '${project.version}'
description: adds scary effects/events to Minecraft
author: CrownedComedian
website: https://www.youtube.com/user/CrownedComedian
main: com.tenjava.entries.CrownedComedian.t3.TenJava

commands:
  spookyevents:
    description: work now?
    usage: /spookyevents <args>

permissions:
  spookyevents.cmd.*:
    description: access to all command permissions
  spookyevents.cmd.CaveBombsSelf:
    description: access to toggle cave bombs on yourself
    